package com.etpl.bbps.common;


	import org.w3c.dom.*;
	import javax.xml.parsers.DocumentBuilder;
	import javax.xml.parsers.DocumentBuilderFactory;
	import org.xml.sax.InputSource;
	import java.io.StringReader;
	import java.util.ArrayList;
	import java.util.HashMap;
	import java.util.List;
	import java.util.Map;

	public class DynamicXmlParser {

	    public Map<String, Object> parseXml(String xmlContent) {
	        Map<String, Object> result = new HashMap<>();
	        try {
	            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
	            DocumentBuilder builder = factory.newDocumentBuilder();
	            Document document = builder.parse(new InputSource(new StringReader(xmlContent)));

	            document.getDocumentElement().normalize();
	            Element root = document.getDocumentElement();

	            // Get the main tag name
	            String mainTagName = root.getNodeName();
	            System.out.println("Main Tag Name: " + mainTagName);

	            // Process the root element and its children
	            result.put(mainTagName, processElement(root));
	        } catch (Exception e) {
	            e.printStackTrace();
	            throw new RuntimeException("Error parsing XML", e);
	        }
	        return result;
	    }

	    private Object processElement(Element element) {
	        NodeList childNodes = element.getChildNodes();
	        Map<String, Object> map = new HashMap<>();
	        for (int i = 0; i < childNodes.getLength(); i++) {
	            Node node = childNodes.item(i);
	            if (node.getNodeType() == Node.ELEMENT_NODE) {
	                Element childElement = (Element) node;
	                String nodeName = childElement.getNodeName();

	                // Recursively process child elements
	                Object value = processElement(childElement);

	                if (map.containsKey(nodeName)) {
	                    // Handle multiple occurrences of the same element
	                    Object existing = map.get(nodeName);
	                    if (existing instanceof List) {
	                        ((List<Object>) existing).add(value);
	                    } else {
	                        List<Object> list = new ArrayList<>();
	                        list.add(existing);
	                        list.add(value);
	                        map.put(nodeName, list);
	                    }
	                } else {
	                    map.put(nodeName, value);
	                }
	            } else if (node.getNodeType() == Node.TEXT_NODE) {
	                // Handle text content
	                String textContent = node.getTextContent().trim();
	                if (!textContent.isEmpty()) {
	                    return textContent;
	                }
	            }
	        }
	        return map;
	    }

	    public static void main(String[] args) {
	        String xmlContent = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n"
	        		+ "<billerInfoResponse>\r\n"
	        		+ "    <responseCode>000</responseCode>\r\n"
	        		+ "    <biller>\r\n"
	        		+ "        <billerId>BILAVAIRTEL001</billerId>\r\n"
	        		+ "        <billerName>AIRTEL</billerName>\r\n"
	        		+ "        <billerCategory>Mobile Prepaid</billerCategory>\r\n"
	        		+ "        <billerAdhoc>true</billerAdhoc>\r\n"
	        		+ "        <billerCoverage>Ind</billerCoverage>\r\n"
	        		+ "        <billerFetchRequiremet>NOT_SUPPORTED</billerFetchRequiremet>\r\n"
	        		+ "        <billerPaymentExactness>Exact</billerPaymentExactness>\r\n"
	        		+ "        <billerSupportBillValidation>OPTIONAL</billerSupportBillValidation>\r\n"
	        		+ "        <supportPendingStatus>No</supportPendingStatus>\r\n"
	        		+ "        <supportDeemed>No</supportDeemed>\r\n"
	        		+ "        <billerTimeout></billerTimeout>\r\n"
	        		+ "        <billerInputParams>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Mobile Number</paramName>\r\n"
	        		+ "                <dataType>NUMERIC</dataType>\r\n"
	        		+ "                <isOptional>true</isOptional>\r\n"
	        		+ "                <minLength>10</minLength>\r\n"
	        		+ "                <maxLength>10</maxLength>\r\n"
	        		+ "                <visibility>true</visibility>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Location</paramName>\r\n"
	        		+ "                <dataType>ALPHANUMERIC</dataType>\r\n"
	        		+ "                <isOptional>true</isOptional>\r\n"
	        		+ "                <minLength>3</minLength>\r\n"
	        		+ "                <maxLength>20</maxLength>\r\n"
	        		+ "                <visibility>true</visibility>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "        </billerInputParams>\r\n"
	        		+ "        <billerAdditionalInfo/>\r\n"
	        		+ "        <billerAmountOptions>BASE_BILL_AMOUNT</billerAmountOptions>\r\n"
	        		+ "        <billerPaymentModes>NEFT, ACCOUNT TRANSFER, CASH, BHARAT QR, PREPAID CARD, WALLET, INTERNET BANKING, DEBIT CARD, AEPS, UPI</billerPaymentModes>\r\n"
	        		+ "        <billerDescription></billerDescription>\r\n"
	        		+ "        <rechargeAmountInValidationRequest>OPTIONAL</rechargeAmountInValidationRequest>\r\n"
	        		+ "        <billerPaymentChannels>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOBB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>AGT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INTB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>ATM</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>POS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BNKBRNCH</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MPOS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BSC</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>KIOSK</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "        </billerPaymentChannels>\r\n"
	        		+ "        <billerAdditionalInfoPayment/>\r\n"
	        		+ "        <planAdditionalInfo/>\r\n"
	        		+ "        <planMdmRequirement>NOT_SUPPORTED</planMdmRequirement>\r\n"
	        		+ "        <billerResponseType>SINGLE</billerResponseType>\r\n"
	        		+ "        <billerPlanResponseParams/>\r\n"
	        		+ "    </biller>\r\n"
	        		+ "    <biller>\r\n"
	        		+ "        <billerId>BILAVJIO000001</billerId>\r\n"
	        		+ "        <billerName>Jio</billerName>\r\n"
	        		+ "        <billerCategory>Mobile Prepaid</billerCategory>\r\n"
	        		+ "        <billerAdhoc>true</billerAdhoc>\r\n"
	        		+ "        <billerCoverage>NAT</billerCoverage>\r\n"
	        		+ "        <billerFetchRequiremet>NOT_SUPPORTED</billerFetchRequiremet>\r\n"
	        		+ "        <billerPaymentExactness>Exact</billerPaymentExactness>\r\n"
	        		+ "        <billerSupportBillValidation>OPTIONAL</billerSupportBillValidation>\r\n"
	        		+ "        <supportPendingStatus></supportPendingStatus>\r\n"
	        		+ "        <supportDeemed></supportDeemed>\r\n"
	        		+ "        <billerTimeout></billerTimeout>\r\n"
	        		+ "        <billerInputParams>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Mobile Number</paramName>\r\n"
	        		+ "                <dataType>NUMERIC</dataType>\r\n"
	        		+ "                <isOptional>false</isOptional>\r\n"
	        		+ "                <minLength>10</minLength>\r\n"
	        		+ "                <maxLength>10</maxLength>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Location</paramName>\r\n"
	        		+ "                <dataType>ALPHANUMERIC</dataType>\r\n"
	        		+ "                <isOptional>false</isOptional>\r\n"
	        		+ "                <minLength>0</minLength>\r\n"
	        		+ "                <maxLength>0</maxLength>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "        </billerInputParams>\r\n"
	        		+ "        <billerAdditionalInfo/>\r\n"
	        		+ "        <billerAmountOptions>BASE_BILL_AMOUNT</billerAmountOptions>\r\n"
	        		+ "        <billerPaymentModes>ACCOUNT TRANSFER, UPI, WALLET, DEBIT CARD, PREPAID CARD, AEPS, IMPS, CASH, NEFT, INTERNET BANKING, BHARAT QR, CREDIT CARD</billerPaymentModes>\r\n"
	        		+ "        <billerDescription></billerDescription>\r\n"
	        		+ "        <rechargeAmountInValidationRequest>NOT_SUPPORTED</rechargeAmountInValidationRequest>\r\n"
	        		+ "        <billerPaymentChannels>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>POS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MPOS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOBB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>AGT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INTB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>KIOSK</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BNKBRNCH</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>ATM</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BSC</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "        </billerPaymentChannels>\r\n"
	        		+ "        <billerAdditionalInfoPayment/>\r\n"
	        		+ "        <planAdditionalInfo/>\r\n"
	        		+ "        <planMdmRequirement></planMdmRequirement>\r\n"
	        		+ "        <billerResponseType></billerResponseType>\r\n"
	        		+ "        <billerPlanResponseParams/>\r\n"
	        		+ "    </biller>\r\n"
	        		+ "    <biller>\r\n"
	        		+ "        <billerId>BILAVMTNL00001</billerId>\r\n"
	        		+ "        <billerName>MTNL Mumbai</billerName>\r\n"
	        		+ "        <billerCategory>Mobile Prepaid</billerCategory>\r\n"
	        		+ "        <billerAdhoc>true</billerAdhoc>\r\n"
	        		+ "        <billerCoverage>MUMBAI</billerCoverage>\r\n"
	        		+ "        <billerFetchRequiremet>NOT_SUPPORTED</billerFetchRequiremet>\r\n"
	        		+ "        <billerPaymentExactness>Exact</billerPaymentExactness>\r\n"
	        		+ "        <billerSupportBillValidation>OPTIONAL</billerSupportBillValidation>\r\n"
	        		+ "        <supportPendingStatus>No</supportPendingStatus>\r\n"
	        		+ "        <supportDeemed>No</supportDeemed>\r\n"
	        		+ "        <billerTimeout></billerTimeout>\r\n"
	        		+ "        <billerInputParams>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Mobile Number</paramName>\r\n"
	        		+ "                <dataType>NUMERIC</dataType>\r\n"
	        		+ "                <isOptional>false</isOptional>\r\n"
	        		+ "                <minLength>10</minLength>\r\n"
	        		+ "                <maxLength>10</maxLength>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Recharge Type</paramName>\r\n"
	        		+ "                <dataType>ALPHANUMERIC</dataType>\r\n"
	        		+ "                <isOptional>false</isOptional>\r\n"
	        		+ "                <minLength>0</minLength>\r\n"
	        		+ "                <maxLength>0</maxLength>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "        </billerInputParams>\r\n"
	        		+ "        <billerAdditionalInfo/>\r\n"
	        		+ "        <billerAmountOptions>BASE_BILL_AMOUNT</billerAmountOptions>\r\n"
	        		+ "        <billerPaymentModes>NEFT, PREPAID CARD, CASH, CREDIT CARD, UPI, DEBIT CARD, IMPS, WALLET, INTERNET BANKING, BHARAT QR, AEPS, ACCOUNT TRANSFER</billerPaymentModes>\r\n"
	        		+ "        <billerDescription></billerDescription>\r\n"
	        		+ "        <rechargeAmountInValidationRequest>NOT_SUPPORTED</rechargeAmountInValidationRequest>\r\n"
	        		+ "        <billerPaymentChannels>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>KIOSK</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BNKBRNCH</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOBB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BSC</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MPOS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INTB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>ATM</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>AGT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>POS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "        </billerPaymentChannels>\r\n"
	        		+ "        <billerAdditionalInfoPayment/>\r\n"
	        		+ "        <planAdditionalInfo/>\r\n"
	        		+ "        <planMdmRequirement></planMdmRequirement>\r\n"
	        		+ "        <billerResponseType></billerResponseType>\r\n"
	        		+ "        <billerPlanResponseParams/>\r\n"
	        		+ "    </biller>\r\n"
	        		+ "    <biller>\r\n"
	        		+ "        <billerId>BILAVMTNL00002</billerId>\r\n"
	        		+ "        <billerName>MTNL Delhi</billerName>\r\n"
	        		+ "        <billerCategory>Mobile Prepaid</billerCategory>\r\n"
	        		+ "        <billerAdhoc>true</billerAdhoc>\r\n"
	        		+ "        <billerCoverage>DELHI</billerCoverage>\r\n"
	        		+ "        <billerFetchRequiremet>NOT_SUPPORTED</billerFetchRequiremet>\r\n"
	        		+ "        <billerPaymentExactness>Exact</billerPaymentExactness>\r\n"
	        		+ "        <billerSupportBillValidation>OPTIONAL</billerSupportBillValidation>\r\n"
	        		+ "        <supportPendingStatus></supportPendingStatus>\r\n"
	        		+ "        <supportDeemed></supportDeemed>\r\n"
	        		+ "        <billerTimeout></billerTimeout>\r\n"
	        		+ "        <billerInputParams>\r\n"
	        		+ "            <paramInfo>\r\n"
	        		+ "                <paramName>Mobile Number</paramName>\r\n"
	        		+ "                <dataType>NUMERIC</dataType>\r\n"
	        		+ "                <isOptional>false</isOptional>\r\n"
	        		+ "                <minLength>10</minLength>\r\n"
	        		+ "                <maxLength>10</maxLength>\r\n"
	        		+ "            </paramInfo>\r\n"
	        		+ "        </billerInputParams>\r\n"
	        		+ "        <billerAdditionalInfo/>\r\n"
	        		+ "        <billerAmountOptions>BASE_BILL_AMOUNT</billerAmountOptions>\r\n"
	        		+ "        <billerPaymentModes>CASH, DEBIT CARD, NEFT, AEPS, IMPS, PREPAID CARD, WALLET, INTERNET BANKING, BHARAT QR, UPI, ACCOUNT TRANSFER, CREDIT CARD</billerPaymentModes>\r\n"
	        		+ "        <billerDescription></billerDescription>\r\n"
	        		+ "        <rechargeAmountInValidationRequest>NOT_SUPPORTED</rechargeAmountInValidationRequest>\r\n"
	        		+ "        <billerPaymentChannels>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BSC</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>INTB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MOBB</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>BNKBRNCH</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>AGT</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>POS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>ATM</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>KIOSK</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "            <paymentChannelInfo>\r\n"
	        		+ "                <paymentChannelName>MPOS</paymentChannelName>\r\n"
	        		+ "                <minAmount>0</minAmount>\r\n"
	        		+ "                <maxAmount>0</maxAmount>\r\n"
	        		+ "            </paymentChannelInfo>\r\n"
	        		+ "        </billerPaymentChannels>\r\n"
	        		+ "        <billerAdditionalInfoPayment/>\r\n"
	        		+ "        <planAdditionalInfo/>\r\n"
	        		+ "        <planMdmRequirement></planMdmRequirement>\r\n"
	        		+ "        <billerResponseType></billerResponseType>\r\n"
	        		+ "        <billerPlanResponseParams/>\r\n"
	        		+ "    </biller>\r\n"
	        		+ "</billerInfoResponse>";
	        DynamicXmlParser parser = new DynamicXmlParser();
	        Map<String, Object> result = parser.parseXml(xmlContent);
	        System.out.println(result);
	    }
	}
